### ISSUE TITLE
Translation issue (Chapter 3.2)

### ISSUE THREAD

**Issue by DavidSonoda** [waylau/Jersey-2.x-User-Guide#3]
3.2. Parameter Annotations (@*Param) 参数注解

### Example 3.8 explanation 1
> 一个接收一个字符串参数的构造函数；

should be
> 有一个接收一个字符串参数的构造函数；

### Example 3.8 explanation 2
> 有一个静态方法或一个命名为 fromstring 的方法

should be
> 有一个命名为 fromstring 或valueOf的静态方法

### Example 3.8 explanation 5
> 在 T 满足上面 2 或者 3 个条件时，将会是 List、Set 或者 SortedSet。这样的集合是只读的。

should be
> 为List\<T\>, Set\<T\>或者SortedList\<T\>, 且在 T 满足上面 2 或者 3 个条件时，将会是 List、Set 或者 SortedSet。这样的集合是只读的。

**Comment by waylau** [comment]
@DavidSonoda   感谢反馈！ 已经采纳
